### PR TITLE
Remove Account Related Routes Etc

### LINKED ISSUE #890: Get rid of accounts related stuff
- [x] Login page
- [x] Register page
- [x] Generate page
- [x] Reset page
- [x] Confirm page
- [x] containers/AccountProvider/sagas/accountLoginSaga?
- [x] services/account?
  * [x] accountService.confirm
  * [x] accountService.getAccount
  * [x] accountService.resendEmail
  * [x] accountService.addWallet
  * [x] accountService.resetWallet
- [x] account.refs?

- [x] react-recaptcha dependency
- [x] mouse entropy component

### PR DESCRIPTION
**Pull request by VonIobro**
- [x] resolves #890

### CODE REVIEW

**Comment by VonIobro** [comment]
@sunify ready to merge, tested with chrome and firefox

**Comment by VonIobro** [comment]
- [ ] tableMenu (since it doesnt log-out or in)

**Comment by sunify** [comment]
@VonIobro ready to merge?

**Comment by VonIobro** [comment]
@sunify yup! Sorry previous message got lost. Tested on Firefox and Chrome, ready to merge.

**Pull request merged**
